@startuml
class com.example.pecl_pcd_final.Entorno {
- Logger logger
- boolean enPausa
- int numHumanos
- ArrayList<Zombie> zombiesTotales
- ListaHilos descanso
- ListaHilos comedor_espera
- ListaHilos comedor_comiendo
- ListaHilos zona_comun
- Lock cerrojoComida
- Condition hayComida
- ConcurrentLinkedQueue<Integer> comidaTotal
- ConcurrentLinkedQueue<Humano> colaComedor
- javafx.scene.control.TextField labelComida
- ArrayList<Tunel> listaTuneles
- ArrayList<ListaHilos> listaTunelesSalir
- ArrayList<ListaHilos> listaTunelesIntermedio
- ArrayList<ListaHilos> listaTunelesEntrar
- ArrayList<ZonaRiesgoHumano> zona_riesgoHumanos
- ArrayList<ListaHilos> zona_riesgoZombie
+ void pausar()
+ void comprobarPausa()
+ void reanudar()
+ void comer(Humano)
+ void actualizarLabelComida()
+ void actualizarComida(int)
+ ListaHilos getDescanso()
+ ListaHilos getComedor_espera()
+ ListaHilos getComedor_comiendo()
+ ListaHilos getZona_comun()
+ ArrayList<Tunel> getListaTuneles()
+ ArrayList<ListaHilos> getListaTunelesSalir()
+ ArrayList<ListaHilos> getListaTunelesIntermedio()
+ ArrayList<ListaHilos> getListaTunelesEntrar()
+ ArrayList<ListaHilos> getZona_riesgoZombie()
+ ListaHilos getTunelSalir(int)
+ ListaHilos getTunelIntermedio(int)
+ ListaHilos getTunelEntrar(int)
+ ZonaRiesgoHumano getZonaRiesgoH(int)
+ int getNumHumanos()
+ void setNumHumanos(int)
+ ArrayList<Zombie> getZombiesTotales()
+ boolean isEnPausa()
+ int getNumRefugio()
+ int getNumTunel(int)
+ int getNumZonaInseguraHumanos(int)
+ int getNumZonaInseguraZombie(int)
+ ArrayList<String> getZombiesLetales()
}


@endumll