@startuml
class com.example.pecl_pcd_final.Tunel {
- Logger logger
- CyclicBarrier barreraTunel
- Lock cerrojoTunel
- Condition puedeAtravesar
- Entorno entorno
- boolean tunelOcupado
- ConcurrentLinkedQueue<Humano> colaParaVolver
- ConcurrentLinkedQueue<Humano> colaParaSalir
+ void salirDesdeRefugio(Humano,int)
+ void volverAlRefugio(Humano,int)
}


@endu