@startuml
class com.example.pecl_pcd_final.HiloGenerador {
- Entorno entorno
- int numHumanosAGenerar
+ void run()
}




com.example.pecl_pcd_final.Thread <|-- com.example.pecl_pcd_final.HiloGenerador
@enduml