@startuml
class com.example.pecl_pcd_final.Humano {
- Logger logger
- int numComida
- boolean marcado
- boolean defendiendose
+ void run()
+ void esperarAtaque()
+ void setNumComida(int)
+ void setMarcado(boolean)
+ void setDefendiendose(boolean)
}




com.example.pecl_pcd_final.Ser <|-- com.example.pecl_pcd_final.Humano
@enduml