@startuml
class com.example.pecl_pcd_final.Zombie {
- Logger logger
- int numMuertes
+ void run()
+ int getNumMuertes()
+ void setNumMuertes(int)
}




com.example.pecl_pcd_final.Ser <|-- com.example.pecl_pcd_final.Zombie
@enduml